name = "FilonResearch"
uuid = "3a284e70-3988-4fde-94af-e81b1d70ca0a"
authors = ["Spencer Lee <leespen1@msu.edu>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CairoMakie = "0.15.7"
LaTeXStrings = "1.4.0"
Polynomials = "4.1.0"
Random = "1.11.0"
SpecialFunctions = "2.6.1"
Test = "1.11.0"
